apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels: 
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: us-central1-docker.pkg.dev/johnny-projectt/tech-ready-demo/payment-microservice:v2
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
