apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "payment-backendconfig"}'
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8081
