apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels: 
        app: order-service
    spec:
      serviceAccountName: common-app-ksa
      containers:
        - name: order-service
          image: us-central1-docker.pkg.dev/johnny-projectt/tech-ready-demo/order-microservice:v3
          ports:
            - containerPort: 8080
          resources:
            requests:
            cpu: "250m"
            memory: "512Mi"
            limits:
            cpu: "500m"
            memory: "1Gi"  
          env:
          - name: SECRET_CREDENTIALS
          value: "projects/johnny-projectt/secrets/app-env-config/versions/latest"
