apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: common-app-ksa  
      containers:
      - name: auth-service
        image: us-central1-docker.pkg.dev/johnny-projectt/tech-ready-demo/auth-microservice:v3
        ports:
        - containerPort: 8083
        env:
        - name: SECRET_CREDENTIALS
          value: "projects/johnny-projectt/secrets/app-env-config/versions/latest"
