apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "product-backendconfig"}'
spec:
  selector:
    app: product-service
  ports:
    - port: 80
      targetPort: 8082
